---
- name: Run Node.js application and install npm dependencies
  hosts: 146.190.36.150
  become: true

  tasks:
    - name: Copy code to the server
      copy:
        src: /var/lib/jenkins/workspace/node-server
        dest: /app/jenkins-node

    - name: Change directory to the application folder
      shell: cd /app/jenkins-node

    - name: Install npm dependencies
      shell: npm install

    - name: Start Node.js application
      shell: npm start
